---

# For Listed DAG Git Repos, clone designated branch or release to DAGS folder
- name: 'CONFIG | DAGS | Clone listed DAG git repositories'
  become_user: "{{ airflow_user_name }}"
  become: true
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ dags_repos_folder }}/{{ item.dest_folder }}"
    clone: true
    force: true
    version: "{{ item.branch_or_release }}"
    recursive: false
  with_items:
    - "{{ dags_git_repositories }}"
  when: (item.branch_or_release | length) > 0

# FOR Listed DAG Git Repos, link them from download destination to configured DAGS folder
- name: 'CONFIG | DAGS | Link dag repository to dags folder'
  become_user: "{{ airflow_user_name }}"
  become: true
  ansible.builtin.file:
    state: link
    path: "{{ dags_folder }}/{{ item.dest_folder }}"
    src: "{{ dags_repos_folder }}/{{ item.dest_folder }}{% if item.dags_folder_name is defined %}/{{ item.dags_folder_name }}{% endif %}"
  with_items:
    - "{{ dags_git_repositories }}"
  when: (item.branch_or_release | length) > 0

# For DAG-Related Git Repos, clone designated branch or release to $HOME
- name: 'CONFIG | DAGS | Clone listed DAG-related git repositories'
  become_user: "{{ airflow_user_name }}"
  become: true
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest_folder }}"
    clone: true
    force: true
    version: "{{ item.branch_or_release }}"
  with_items:
    - "{{ dags_related_git_repositories }}"


# Manage DAGs system dependencies
- name: 'INSTALL | Manage DAG system dependencies'
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ airflow_dag_system_dependencies }}"
